# Generated by Django 5.2.2 on 2025-06-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_landmarks',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
