# Generated by Django 5.2.2 on 2025-06-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userprofile_face_landmarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='face_landmarks',
            new_name='face_embedding',
        ),
    ]
