# Generated by Django 5.2.2 on 2025-06-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_role_documentsharingrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsharingrequest',
            name='document_path',
        ),
        migrations.AddField(
            model_name='documentsharingrequest',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.document'),
        ),
    ]
