# Generated by Django 5.2.2 on 2025-06-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_documentsharingrequest_document_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('releve', 'Relevé de notes'), ('certificat', 'Certificat de scolarité'), ('attestation', 'Attestation'), ('cv', 'CV'), ('paiement', 'Justificatif de paiement'), ('facture', 'Facture'), ('devoir', 'Devoir'), ('autre', 'Autre')], max_length=20),
        ),
    ]
