# Generated by Django 5.2.2 on 2025-06-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_document_type_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
