# Generated by Django 5.2.2 on 2025-06-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_document_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='audio_file',
        ),
    ]
