# Generated by Django 5.2.2 on 2025-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_document_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('autre', 'Autre')], default='pdf', max_length=10),
        ),
    ]
