# Generated by Django 5.2.2 on 2025-06-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_document_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='format',
        ),
    ]
