# Generated by Django 5.2.2 on 2025-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_document_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsharingrequest',
            name='audio_path',
            field=models.CharField(blank=True, help_text='Chemin du fichier audio si applicable', max_length=500, null=True),
        ),
    ]
