# Generated by Django 5.2.2 on 2025-07-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Remarque sur le document partagé', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sharing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='app.documentsharingrequest')),
            ],
        ),
    ]
